### ISSUE TITLE
Try out METAL and add to compilation instructions

### ISSUE THREAD

**Issue by simonw** [simonw/llm-llama-cpp#7]
Tip from https://mas.to/@goranmoomin/110820724235904467

>  From my last time trying out llama.cpp & Llama 2, I don't think the text generation should be taking ~20s if you're using the Metal-accelerated implementation.
>
> Sorry if you’ve already tried… but have you tried giving the env vars `CMAKE_ARGS='-DLLAMA_METAL=on' FORCE_CMAKE=1` when installing llama-cpp-python? (ref https://github.com/abetlen/llama-cpp-python )

**Comment by mtpettyp** [comment]
I suspect that you will also need to be able to set values for `n_gpu_layers`

See "(6) run the llama-cpp-python API server with MacOS Metal GPU support" in:
https://github.com/abetlen/llama-cpp-python/blob/main/docs/install/macos.md

**Comment by simonw** [comment]
I just tried this:

```bash
CMAKE_ARGS='-DLLAMA_METAL=on' FORCE_CMAKE=1 \
  llm install llama-cpp-python --force-reinstall --upgrade --no-cache-dir
```
Using the new options I added in:
- https://github.com/simonw/llm/issues/146

Activity Monitor doesn't show the process using any GPU. I think that's because it also needs that `n_gpu_layers` option.

**Comment by simonw** [comment]
Note that if you haven't installed `llama-cpp-python` at all yet you won't need the `--force-reinstall` feature - you should just be able to do this:
```bash
CMAKE_ARGS='-DLLAMA_METAL=on' FORCE_CMAKE=1 \
  llm install llama-cpp-python
```

**Comment by simonw** [comment]
I'm not sure what `n_gpu_layers` should be set to - lots of variance in https://github.com/search?q=n_gpu_layers+language%3APython&type=code&l=Python

I'm going to try `1` and see how that goes.

**Comment by John-Lin** [comment]
just came across this issue from langchain docs mention that 

> n_gpu_layers = 1  # Metal set to 1 is enough.

https://python.langchain.com/docs/integrations/llms/llamacpp#metal

**Comment by simonw** [comment]
I tried this:
```diff
diff --git a/llm_llama_cpp.py b/llm_llama_cpp.py
index f2fc977..c38d7f6 100644
--- a/llm_llama_cpp.py
+++ b/llm_llama_cpp.py
@@ -226,7 +226,10 @@ class LlamaModel(llm.Model):
     def execute(self, prompt, stream, response, conversation):
         with SuppressOutput(verbose=prompt.options.verbose):
             llm_model = Llama(
-                model_path=self.path, verbose=prompt.options.verbose, n_ctx=4000
+                model_path=self.path,
+                verbose=prompt.options.verbose,
+                n_ctx=4000,
+                n_gpu_layers=1,
             )
             if self.is_llama2_chat:
                 prompt_bits = self.build_llama2_chat_prompt(prompt, conversation)
```
And ran this:
```bash
llm -m l2c 'Say hello' --system 'You are a humanoid cat'
```
And got this crash: https://gist.github.com/simonw/5d619132f025b83f570c3afcf1d0fbbf

**Comment by simonw** [comment]
I ran this in the same virtual environment as `llm`:
```bash
python -m llama_cpp.server \
  --model "$(llm llama-cpp models-dir)/llama-2-7b-chat.ggmlv3.q8_0.bin"
```
This started a server - hitting http://localhost:8000/docs provided a UI for executing a prompt, which worked without crashing.

Then I tried this:
```
python -m llama_cpp.server \
  --model "$(llm llama-cpp models-dir)/llama-2-7b-chat.ggmlv3.q8_0.bin" \
  --n_gpu_layers 1
```
This time the server crashed when I tried to execute a prompt.

**Comment by simonw** [comment]
I've not yet tried the miniconda stuff in https://github.com/abetlen/llama-cpp-python/blob/main/docs/install/macos.md

If anyone manages to successfully follow the instructions in https://github.com/abetlen/llama-cpp-python/blob/main/docs/install/macos.md and gets this working please let me know!

**Comment by rollwagen** [comment]
Got it working using the GPU (on M1 Pro Laptop).

Using `llm` in pipx environment (installed with `pipx install llm`), then:

```sh
CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1  pipx runpip llm install --upgrade --force-reinstall llama-cpp-python --no-cache-dir
```

```sh
llm install llama-cpp-python
```

Added the parameter `n_gpu_layers=1` here https://github.com/simonw/llm-llama-cpp/blob/main/llm_llama_cpp.py#L229

```sh
llm llama-cpp download-model \
  https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q4_0.bin \
  --alias llama2-7b-q4-cpp
```

To try e.g. `cat main.go | llm -m llama2-7b-q4-cpp -s "Explain this code"`

In the Activity Monitor app under "Window > GPU History" you nicely see the GPU activity spiking during inference.

_Important_: it only worked for me using the **.q4** model, with the 'q8' model it also crashes.

**Comment by AndreasKunar** [comment]
For me llm-llama-cpp ran on the gpu like llama.cpp (e.g. q4_0 models) with the following modifications:

1) after installing all run the following lines to compile llama-cpp-python with metal support:
pip uninstall llama-cpp-python -y
CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install -U llama-cpp-python --no-cache-dir

2) modify llama-cpp-python (as in the current source):
line 229 (where you create the llm_model, and have parameters): add gpu-enable
, n_gpu_layers=1
line 237 (where you call the model): add a larger max for answering tokens (default 128, is to shortin my opinion) before the closing ')'
, max_tokens=400

Since enabling Metal reduces the number of useable models (one needs to study the README.md for the model on huggingface before downloading), just not doing step 1) or using a non-Metal-compiled llama-cpp-python version solves the issue (the parameter just gets ignored), albeit with slower run-time.

P.S. I'm quite new to github, don't now how to write a pull request yet, so commenting on the issue instead.

**Comment by John-Lin** [comment]
My environment is MacBook Pro M1 with 16GB RAM. I tried modify `llm_llama_cpp.py` with `n_gpu_layers=1` parameter in `Llama` class and found GPU is busy i think it works!

```
--- a/llm_llama_cpp.py
+++ b/llm_llama_cpp.py
@@ -226,7 +226,7 @@ class LlamaModel(llm.Model):
     def execute(self, prompt, stream, response, conversation):
         with SuppressOutput(verbose=prompt.options.verbose):
             llm_model = Llama(
-                model_path=self.path, verbose=prompt.options.verbose, n_ctx=4000
+                model_path=self.path, verbose=prompt.options.verbose, n_ctx=4000, n_gpu_layers=1
             )
```

**Comment by AndreasKunar** [comment]
> My environment is MacBook Pro M1 with 16GB RAM. I tried modify `llm_llama_cpp.py` with `n_gpu_layers=1` parameter in `Llama` class and found GPU is busy i think it works!
> 
> It appears that the output results are not being streamed. Instead, it waits for the entire output results and responds all at once.
> 
...

I'm not experienced enough in Python, especially with "yield" inside loops (still learning some of the stranger things in this language). A similar llama-cpp-python call like the current line 237-243 worked for me in a test-program for streaming-printing the response token by token (no yield, directly printing). With streaming=true, the __call__ to the llm for yielded for me just one element for each returned item, so the for seems redundant. And for stream=False, the return-result looked entirely different. Not sure this helps.

**Comment by imaurer** [comment]
FYI for people wondering what the definitive list of supported Metal quantizations:

https://github.com/ggerganov/llama.cpp/discussions/2320#discussioncomment-6515496

F16
Q6_K
Q5_K
Q4_K
Q4_1
Q4_0
Q3_K
Q2_K

**Comment by simonw** [comment]
Fixes for this are now released in the new beta: https://github.com/simonw/llm-llama-cpp/releases/tag/0.2b0

I updated the README too: https://github.com/simonw/llm-llama-cpp/blob/0.2b0/README.md#installation

I'm looking for confirmation from other people that this all works as expected before I ship a non-beta.

**Comment by simonw** [comment]
This seems to work correctly.
